# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - dev
  schedule:
  - cron:  '*/5 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: npm install
      run: npm ci
#    - name: build data
#      run: node scripts/build-origin.js
    - name: npm run build
      run: npm run build
    - name: npm run test
      run: npm run test
    # - name: deploy to master branch
    #   run: npm run deploy
